spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: roland
    password: '!'isRoland
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database: MYSQL
    hibernate: 
      ddl-auto: update